### Get all the available movies
GET http://localhost:1234/movies

### Get movies by id.
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Get all the movies from the same genre.
GET http://localhost:1234/movies?genre=ACTION

### Create a movie
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "Sonic 3",
    "year": 2024,
    "director": "Tails",
    "duration": 160,
    "poster": "https://preview.redd.it/another-new-sonic-3-poster-tickets-confirmed-to-be-sold-v0-3em2h4oico1e1.jpg?width=1080&crop=smart&auto=webp&s=ce4f96c1439eab6fd3d72c13064bc11fb65e1b1f",
    "genre": ["Action", "Comedy", "Adventure", "Drama"],
    "rate": 10
}

### To change an attribute
PATCH http://localhost:1234/movies/f49d7219-a809-491b-be5d-7186026dec84
Content-Type: application/json

{
    "year": 2024
}

### To delete a movie
DELETE http://localhost:1234/movies/f49d7219-a809-491b-be5d-7186026dec84

### ---------------------------------------

### Register a new User.
POST http://localhost:1234/auth/register
Content-Type: application/json

{
    "username": "123",
    "password": "12345678",
    "email": "loco@gmail.com"

}

### Login
POST http://localhost:1234/auth/login
Content-Type: application/json

{
    "username": "solerus",
    "email": "solerusoficial@gmail.com",
    "password": "testingWebsite23"

}

### Update the Users data
PATCH http://localhost:1234/auth/update/8ec517d3-7d2b-4c24-b009-b1f53717d71d
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlYzUxN2QzLTdkMmItNGMyNC1iMDA5LWIxZjUzNzE3ZDcxZCIsImlhdCI6MTc0MjkwNTUxMiwiZXhwIjoxNzQyOTA5MTEyfQ.DTrcf4Si664ZthpgkNI99RLMMr03_l5PvPnMwHMieDw


{
    "password": "abcdefghi"
}

### PROMOTE USER.
PATCH http://localhost:1234/auth/promote/8ec517d3-7d2b-4c24-b009-b1f53717d71d
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZiZjZlYWU4LTJlYmMtNDhiZi1iNjE2LWVhYThkMjM3ZWQ4NiIsImlhdCI6MTc0MjkwNjAyMCwiZXhwIjoxNzQyOTA5NjIwfQ.uY6cHYuPwvBNahBWEPwRISjY97509fI59IDczVLPOxw

### Logout
POST http://localhost:1234/auth/logout
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlYzUxN2QzLTdkMmItNGMyNC1iMDA5LWIxZjUzNzE3ZDcxZCIsImlhdCI6MTc0Mjg0NjAyMiwiZXhwIjoxNzQyODQ5NjIyfQ.8V0h7a7vTrE94sz1Mr6goJlFwyWqax5swlLE4XSlrjs